version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    restart: unless-stopped
  service:
    build:
      context: "."
    env_file:
      - ".env"
    ports:
      - "8088:8080"
    restart: unless-stopped
    depends_on:
      - postgres
